name: Docker Image Auto Release

on:
  workflow_dispatch:
    inputs:
      imageTag:
        type: string
        description: Image tag
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push server
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: aitbase/flowise-ai:${{ github.event.inputs.imageTag }}